.PHONY: clean All

All:
	@echo "----------Building project:[ backtracking - Debug ]----------"
	@cd "backtracking" && "$(MAKE)" -f  "backtracking.mk"
clean:
	@echo "----------Cleaning project:[ backtracking - Debug ]----------"
	@cd "backtracking" && "$(MAKE)" -f  "backtracking.mk" clean
